server:
  port: 8080

spring:
  application:
    name: recipe-library
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 20
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false

springdoc:
  packages-to-scan: com.recipelibrary.api.controller
  paths-to-match: /recipe-library/v1/**